### ISSUE TITLE
Tracking: Mobile Support (e.g. Firefox for Android)

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1183]
This issue aims for better support under mobile platforms, such as Firefox for Android.

The `chrome.browserAction` API is [not fully supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1330159) in Firefox for Android right now. Specifically, popup is [not implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1387026).

To open the popup, please select the `Omega: ...` Item in the menu and it will open popup as a tab. The menu item is shown in the hamburger menu, on the very bottom, with [NO ICON](https://bugzilla.mozilla.org/show_bug.cgi?id=1370303) associated. There is no way to close the popup so the page just reloads when you select something.

As for the good news, the switching part and proxy settings actually work. Once the proxy has been selected via the popup, you can visit a website to confirm. You will probably need to refresh the page manually.

SwitchyOmega also tries to show you the actual profile used for each tab when you use auto switch, but such changes are not reflected immediately upon navigation (probably due to some menu caching). For now, please just switch to another tab and switch back to see the updated text.

Further improvements:

- [ ] Menu Item Text is not localized.
- [ ] Optimize options page elements for narrow screen. Currently, there are some tables too wide to display.
- [ ] Improve the tutorial for narrow screen. Or just don't show it?

**Comment by FelisCatus** [comment]
Debugging on Firefox for Android
---------------------------------------------

To get the error log, please open the options page by clicking on the menu item, click on SwitchyOmega link on the very top, and then click on the `Save error log` button. Thanks!

To debug, please enable `Debugging over WiFi` 
(or USB if you prefer) in `Menu > Settings > Advanced > Developer tools`. Then, open `Menu > Web developer > WebIDE` on your desktop Firefox Nightly and click on your device. You can type `localStorage.log` in the console to get the error log if the options page won't work.

**Comment by InvisibleRain** [comment]
It seems that all the three issues were fixed by Mozilla:
1. https://bugzilla.mozilla.org/show_bug.cgi?id=1330159
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1387026
3. https://bugzilla.mozilla.org/show_bug.cgi?id=1370303

SwitchyOmega now works fine on Firefox Android (and way better than FoxyProxy)

The features that don't work:
+ All file export functions, including:
  + Make backup
  + Publish rule list
  + Export PAC
  + Save error log

The issue is related to WebExtensions [downloads API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads#browser_compatibility) being removed from Firefox on Android.
Although, this issue is unfixable in conventional ways, it is inherently minor as the Sync Feature makes it possible to export and backup all the neccessary files from Firefox desktop.

Thus, publishing this extension for Android would greatly improve user experience and potentialy attract new contributors.
![image](https://github.com/FelisCatus/SwitchyOmega/assets/47538801/41504690-1fcd-4f30-83f2-cfbd59f43790)
